# Generated by Django 4.0.dev20210521113437 on 2021-07-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(choices=[('McLaren', 'McLaren'), ('Ferrari', 'Ferrari'), ('Morgan', 'Morgan'), ('Maserati', 'Maserati')], default='Customer', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FGcode', models.CharField(max_length=10)),
                ('part_id', models.CharField(default='', max_length=120)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.customer')),
            ],
            options={
                'ordering': ['FGcode'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=7)),
                ('order_quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('pack_number', models.CharField(max_length=10)),
                ('traceability_required', models.BooleanField(default=True)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='records.customer')),
                ('part_FG', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_fgs', to='records.part')),
            ],
        ),
        migrations.CreateModel(
            name='PartInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=11)),
                ('job_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_parts', to='records.wallet')),
                ('part_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='records.part')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(choices=[('Forming', 'Forming'), ('Trimming', 'Trimming'), ('Chemi-Clean', 'Chemi-Clean'), ('Re-Strike', 'Re-Strike'), ('Goods-in Inspection', 'Goods-in Inspection'), ('Pre-Assembly', 'Pre-Assembly'), ('Assembly', 'Assembly'), ('Hemming', 'Hemming'), ('A-Class', 'A-Class'), ('Gap and Flush', 'Gap and Flush'), ('Heat Treatment', 'Heat Treatment'), ('Final Inspection', 'Final Inspection')], max_length=120)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('operation_status', models.CharField(choices=[('Passed', 'Passed'), ('Scrapped', 'Scrapped'), ('Quarantined', 'Quarantined')], default='What is the part status?', max_length=120)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('processed_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='records.partinstance')),
            ],
            options={
                'ordering': ['operation_name'],
            },
        ),
    ]
