# Generated by Django 4.0.dev20210521113437 on 2021-07-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_id',
        ),
        migrations.AddField(
            model_name='wallet',
            name='part_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
