# Generated by Django 4.0.dev20210521113437 on 2021-11-02 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_part_part_id_wallet_part_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='comments',
            field=models.TextField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='records.customer'),
        ),
    ]
