# Generated by Django 4.0.4 on 2022-05-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_operation_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_name',
            field=models.CharField(choices=[('Forming', 'Forming'), ('Trimming', 'Trimming'), ('Chemi-Clean', 'Chemi-Clean'), ('Re-Strike', 'Re-Strike'), ('Goods-in Inspection', 'Goods-in Inspection'), ('Pre-Assembly', 'Pre-Assembly'), ('Assembly', 'Assembly'), ('Hemming', 'Hemming'), ('A-Class', 'A-Class'), ('Gap and Flush', 'Gap and Flush'), ('Heat Treatment', 'Heat Treatment'), ('Final Inspection', 'Final Inspection')], max_length=120, unique=True),
        ),
    ]
